nodeLinker: pnp

packageExtensions:
  "@auth/drizzle-adapter@*":
    peerDependencies:
      drizzle-orm: "*"
  "@testing-library/jest-dom@*":
    peerDependencies:
      vitest: "*"
  "drizzle-kit@*":
    peerDependencies:
      drizzle-orm: "*"
      postgres: "*"
  "eslint-config-next@*":
    peerDependencies:
      next: "*"
